### ISSUE TITLE
Worked code example?

### ISSUE THREAD

**Issue by petemounce** [bazaarvoice/aws-cfn-custom-resource#6]
I'd find it really valuable to have an example to refer to that
* handled create / update / delete of a resource
* returned data for the CloudFormation to access via `GetAtt` - I haven't been able to understand where to plug that in so far.

For example, I'm creating a CR to manage an Elasticsearch Domain:
```js
exports.handleCreate = function(event) {
  return es()
    .createElasticsearchDomain(createParams(event))
    .then(function(result) {
      return tag(result, event.ResourceProperties);
    })
    .catch(console.error);
};

// and elsewhere
exports.tag = function(data, rp) {
  var tags = [
    {Key: 'environment:name', Value: rp.EnvironmentName},
    {Key: 'feature', Value: rp.FeatureName},
    {Key: 'tenant', Value: rp.Tenant}
  ]
  return es()
    .addTags({
      ARN: data.DomainStatus.ARN,
      TagList: tags
    })
    .catch(console.error)
}

function es() {
  var session = new resource.aws.Session();
  return session.client('ES');
}
exports.es = es;
```

I want to return the domain-name that is available from the response of the `createElasticsearchDomain` call, and pass through the tags stage - but I'm not sure how to achieve that (which I recognise is my ignorance of node/js/promises rather than any problem I'm having with your module!).

**Comment by dump247** [comment]
The result of the promise should be an object. There are two keys in the returned object, both are optional: `data` and `physicalResourceId`. The first key, `data` is an object of key/value pairs which are exposed via the `GetAtt` function. The second key, `physicalResourceId`, is returned via the `Ref` function. The physical resource id does not have to be unique, but has the distinction that if an update returns a different physical resource id, cloud formation will issue a delete event for the previous physical resource id. At first glance, it seems reasonable to return the domain as the physical resource id.

For example:

```javascript
exports.handleCreate = function (event) {
  return es()
  .createElasticsearchDomain(createParams(event))
  .get('DomainStatus')
  .then(function (result) {
    return tag(result, event.ResourceProperties)
           .thenResolve(result);
  })
  .then(function (result) {
    return {
      physicalResourceId: result.DomainName,
      data: {
        EndPoint: result.Endpoint
      }
    };
  });
};
```

One other thing to note is that `catch` ends propagation of an error. When you catch the error you prevent the resource from reporting the failure to cloud formation.

I now run ResourceProperties through [jsonschema](https://www.npmjs.com/package/jsonschema) to catch invalid input up front.

Hope that helps. I agree that I should add some examples. Let me know if you have any other questions or issues.

**Comment by petemounce** [comment]
@dump247 thanks, that's great. I'd missed that the object should have a `data` key.

re: catching errors - if I rethrow, is that sensible? eg
```js
    .catch(function(e) {
      self.log.error({err: e}, 'error'); // i'm using bunyan too
      throw e;
    });
```

**Comment by dump247** [comment]
That looks correct.
